#!/bin/sh

set -e

cd "$(dirname "$0")"

TIMEOUT=${1:-5}

if [ -e /dev/mtdblock4 ]; then
    ROOT_DEVICE=/dev/mtdblock4
else
    ROOT_DEVICE=mtd4
fi

MAC_ADDRESS=$(/sbin/ifconfig |
    sed -n '/^eth0.*HWaddr /{s///;p;q;}')
IP_ADDRESS=$(/sbin/ifconfig |
    sed -n '/^eth0/{n;s/^.*inet addr://;s/ .*$//;p;}')
NET_MASK=$(/sbin/ifconfig |
    sed -n '/^eth0/{n;s/^.*Mask://;s/ .*$//;p;}')


NEW_ENV=/tmp/mtd1.new
trap 'rm $NEW_ENV' EXIT

cat <<EOF |
baudrate=115200
bootargs=root=$ROOT_DEVICE console=ttyS0,115200 mem=64M
bootcmd=bootm 80000
bootdelay=$TIMEOUT
ethaddr=$MAC_ADDRESS
ipaddr=$IP_ADDRESS
netmask=$NET_MASK
serverip=172.23.240.3
stdin=serial
stderr=serial
stdout=serial
EOF
./makeenv 40000 4000 > $NEW_ENV

cat $NEW_ENV | ./readenv

dd if=/tmp/mtd1.new of=/dev/mtdblock1
sync

#./readenv

