#!/bin/sh

# Script for configuring the network and the post install script.  As this is
# a little involved, it is placed in a separate script.

HERE="$(dirname "$0")"
. "$HERE"/functions

IPADDR="$(read_config ipaddr)"
NETMASK="$(read_config netmask)"
GATEWAY="$(read_config gatewayip)"
HOSTNAME="$(read_config hostname)"
# Compute the network and broadcast.  
eval $(ipcalc -nb $IPADDR $NETMASK)

echo "Configuring network $IPADDR/$NETMASK"
cat <<EOF >>/mnt/mtd4/etc/network/interfaces

auto eth0
iface eth0 inet static
    address $IPADDR
    network $NETWORK
    netmask $NETMASK
    broadcast $BROADCAST
EOF

if [ -n "$GATEWAY" ]; then
    echo "Configuring gateway $GATEWAY"
    echo "    gateway $GATEWAY" >>/mnt/mtd4/etc/network/interfaces
fi

echo "Configuring host name $HOSTNAME"
echo "$HOSTNAME" >/mnt/mtd4/etc/hostname


# Finally configure the post installation script.
TFTP_SERVER="$(read_config serverip)"
POST_SCRIPT="$(read_config postscript)"

echo "Configuring post install: "
echo "  TFTP: $TFTP_SERVER,"
echo "  script: $POST_SCRIPT"
[ -n "$POST_SCRIPT" ]  &&  cat <<EOF >/mnt/mtd4/etc/post-install
TFTP_SERVER='$TFTP_SERVER'
POST_SCRIPT='$POST_SCRIPT'
EOF
