#!/bin/sh

# Script to install libera on target system
BIN=/installer/linux-arm_el

# First create mount points.
mkdir -p /mnt/mtd3 /mnt/mtd4

# Erase the variable partition first so that we can mount it and log the
# rest to it.
flash_eraseall -j /dev/mtd3
mount -t jffs2 mtd3 /mnt/mtd3

# Log the rest to mtd3.
exec >/mnt/mtd3/install.log 2>&1
echo Starting complete Libera upgrade

# Install configured kernel to mtd2, but only if necessary
if head -c $(stat -c%s /uImage) /dev/mtd2 | $BIN/bindiff /uImage; then
    echo Kernel already installed
else
    echo Installing the new kernel
    flashcp -v /uImage /dev/mtd2
fi

# Erase mtd4 and install new file system.
echo Erasing target rootfs
flash_eraseall -j /dev/mtd4
mount -t jffs2 mtd4 /mnt/mtd4
cd /mnt/mtd4
echo Installing new file system
cpio -i </imagefile.cpio

# Copy the network configuration into the new file system.
echo Configuring network
/installer/configure-network

# Update the u-boot configuration for the new installation.  We carry
# everything across apart from the boot instructions.
echo Updating u-boot configuration
/installer/configure-boot -Vw \
    -fipaddr -fnetmask -fgatewayip -fhostname -fserverip \
    -vbootargs='console=ttyS0,115200 ro root=mtd4 rootfstype=jffs2' \
    -vbootcmd='bootm 80000'

echo Installation complete, rebooting
sync
reboot
