EXTRA_CFLAGS += -DEBPP -DDEBUG=0
# ccflags-y += -O2 -Werror -Wextra
EXTRA_CFLAGS += -Wno-declaration-after-statement -Wno-unused-parameter
# ccflags-y += -Wno-missing-field-initializers

EXTRA_CFLAGS += -DLIBERA_BASE_VERSION='"$(LIBERA_BASE_VERSION)"'

OBJS = libera_main.o libera_cfg.o libera_dd.o libera_adc.o \
       libera_fa.o libera_sa.o libera_pm.o libera_event.o libera_dsc.o \
       ebpp.o

obj-m := libera.o
libera-objs := $(OBJS)
