#!/bin/sh

# Configuration to mount extra fstab like files.  Takes its configuration
# from environment variable FSTABS in /etc/defaults/mount-local.

. /etc/init.d/functions

do_start()
{
    for fstab in $FSTABS; do
        sed '/^#/d; /^[ \t]*$/d' $fstab |
        while read spec file type opts rest; do
            mount -t $type -o $opts $spec $file
        done
    done
}

do_stop()
{
    for fstab in $FSTABS; do
        sed '/^#/d; /^[ \t]*$/d' $fstab |
        while read spec file type opts rest; do
            umount $file
        done
    done
}

do_start_stop "$1" 'local mounts'
