EXTRA_CFLAGS += -DEBPP -DDEBUG=0
EXTRA_CFLAGS += -O2 -Werror -Wextra
EXTRA_CFLAGS += -Wno-declaration-after-statement -Wno-unused-parameter
EXTRA_CFLAGS += -Wno-missing-field-initializers

obj-m := msp.o
msp-objs := msp_main.o
# msp-objs := simple.o
