ccflags-y += -DEBPP -DDEBUG=0
ccflags-y += -O2 -Werror -Wextra
ccflags-y += -Wno-declaration-after-statement -Wno-unused-parameter
ccflags-y += -Wno-missing-field-initializers

ccflags-y += -DLIBERA_BASE_VERSION='"$(LIBERA_BASE_VERSION)"'

obj-m := msp.o
msp-objs := msp_main.o
