#!/bin/sh

# Script to coordinate the upgrade of Libera.

HERE="$(dirname "$0")"
U_BOOT="$HERE"/../u-boot-upgrade

Error()
{
    echo >&2 "$(hostname): $@"
    exit 1
}


INSTALL_SCRIPT='boot-script-installer-@@LIBERA_BASE_VERSION@@.image'


pre_upgrade() { :; }  # Default pre-upgrade action: do nothing
TFTP_PREFIX=

. "$HERE"/upgrade-defaults


while getopts 'hs:t:i:p:' option; do
    case "$option" in
        h)  cat <<EOF
Usage: $0 [<options>] confirm [<post-install-arg>]

Runs Libera upgrade script.  The following options can be specified:
    -s<install-script>
        The install script is $INSTALL_SCRIPT,
        and can be overridden here.  This file must be present on
        the specified TFTP server.
    -t<tftp-server>
        The configured TFTP server is $TFTP_SERVER; this can be overridden
        here.  The server must be present.  This must be an decimal dotted
        IP address.
    -i<post-install-script>
        The post installation script is $POST_SCRIPT,
        which can be overridden here.  If this is empty then no post
        installation will be done.
    -p<tftp-prefix>
        The tftp prefix is appended to each file fetched from the tftp
        server.  The current prefix is: '$TFTP_PREFIX'.

Before running the upgrade script it is important to ensure that the
following files are already present on the TFTP server.  If the TFTP server
cannot be reached or any of these files are missing the upgrade will fail
and it will be necessary to reconfigure u-boot by connecting to the serial
port.

The following files must be present on the TFTP server at $TFTP_SERVER:

    $TFTP_PREFIX$INSTALL_SCRIPT
        This is the u-boot installation script that will be executed to
        load the two files below.
        
    ${TFTP_PREFIX}uImage-libera-@@KERNEL_RELEASE@@
        Kernel image that will be loaded by the installer.  This image is
        also built into the installation image.
        
    ${TFTP_PREFIX}imagefile-installer-@@LIBERA_BASE_VERSION@@.cpio.gz
        Installation image: this is a complete boot image.  After booting,
        the Libera kernel and root file system will be upgraded and Libera
        will reboot into the new system.

    $TFTP_PREFIX$POST_SCRIPT
        Post installation script: this is a file in tar.gz format containing
        at least an executable file post-script.sh.  This will be executed
        immediately after successfully booting Libera for the first time.

Note that static network configuration will be preserved over the
installation, but all other settings will be erased.
EOF
            exit 0
            ;;
        s)  INSTALL_SCRIPT="$OPTARG" ;;
        t)  TFTP_SERVER="$OPTARG" ;;
        i)  POST_SCRIPT="$OPTARG" ;;
        p)  TFTP_PREFIX="$OPTARG" ;;
        *)  Error Invalid option.  Try -h for help.
    esac
done


shift $((OPTIND-1))
[ "$1" = confirm ]  ||
    Error Try -h for help.

SCRIPT_ARGS="$2"

[ "$TFTP_SERVER" = unknown ] &&
    Error Must specify TFTP server

# First check that the u-boot is properly upgraded
"$U_BOOT"/update-u-boot -w ||
    Error Something went wrong with u-boot update.

# Run the pre-upgrade action before we finally commit
pre_upgrade  ||
    Error Pre upgrade failed

# Configure to boot from installer
[ -n "$POST_SCRIPT" ]  &&  POST_SCRIPT="$TFTP_PREFIX$POST_SCRIPT"
BOOT_CMD="tftpboot a0000000 $TFTP_PREFIX$INSTALL_SCRIPT && autoscr a0000000"
"$U_BOOT"/configure-boot -w \
    -dbootargs \
    -vbootcmd="$BOOT_CMD" \
    -vserverip="$TFTP_SERVER" -vpostscript="$POST_SCRIPT" \
    -vscriptargs="$SCRIPT_ARGS" -vtftpprefix="$TFTP_PREFIX"

# We are ready to go!
reboot -f
