# Makefile for kernel builds.


include $(TOP)/scripts/COMMON

export CROSS_COMPILE
export ARCH = arm

# The kernel will have been built using the kernel build tool.  Ask it kindly
# where it put the build; we need this for module builds!
KBUILD_OUTPUT = $(shell \
    make -s -C $(KERNEL_BUILD) TARGET=libera-2.6 print-build-dir)

TARGET_DIR ?= /home/libera/nfs/testing


default:

$(O):
	mkdir -p $(O)
	ln -fs $(wildcard $(patsubst %,$(CURDIR)/%, *.[c,h] $(MAKEFILE))) $(O)

default: $(O)
	make -C $(KBUILD_OUTPUT) M=$(O)

install:
	cp $(patsubst %,$(O)/%,$(TARGETS)) $(TARGET_DIR)

# install:
# 	make -C $(KBUILD_OUTPUT) M=$(CURDIR) \
#             INSTALL_MOD_PATH=$(CURDIR)/testing modules_install V=1

clean:
	rm -rf $(O)
