# Makefile for kernel builds.

include $(TOP)/CONFIG
include $(TOP)/scripts/COMMON
include $(TOP)/scripts/COMPILE

export CROSS_COMPILE
export ARCH = arm

# Make the version of Libera Base visible to the module being built.
export LIBERA_BASE_VERSION


TARGET_DIR = $(INSTALL_ROOT)/$(COMPONENT)


default:

# Building kernel modules out of tree is annoyingly tricky.  It seems the
# most practical way is to make links to all the source files in the build
# directory; not so great.
$(O):
	mkdir -p $(O)
	ln -fs $(wildcard $(patsubst %,$(CURDIR)/%, *.[c,h] $(MAKEFILE))) $(O)

$(TARGETS): $(O)
	$(MAKE) -C $(KBUILD_OUTPUT) M=$(O) 

install: $(TARGETS)
	rm -rf $(TARGET_DIR)
	mkdir -p $(TARGET_DIR)
	cp $(patsubst %,$(O)/%,$(TARGETS)) $(TARGET_DIR)

# The following appears to be an "official" way to install the modules, but
# it seems somewhat overkill.
# 	$(MAKE) -C $(KBUILD_OUTPUT) M=$(O) \
#              INSTALL_MOD_PATH=$(TARGET_DIR) modules_install V=1

default: $(TARGETS)

clean:
	rm -rf $(O)

clean-all: clean
	rm -rf $(TARGET_DIR)

.PHONY: clean clean-all default

# vim: set filetype=make:
