#!/bin/sh

# Installation script to be run on Libera to install Libera base files.

HERE="$(dirname "$0")"


Error()
{
    echo >&2 "$@"
    exit 1
}

detect_brilliance()
{
    # The test is very simple: the Brilliance RF board uses an adm1023
    # temperature sensor.
    [ -e /sys/bus/i2c/devices/0-0018 ]  && 
    [ "$(cat /sys/bus/i2c/devices/0-0018/name)" = adm1023 ]
}


[ "$(uname -m)" = armv5tel ]  ||
    Error This should be run on Libera

grep -q '^DLS rootfs' /etc/version  ||
    Error This should not be run on an i-Tech Libera

. "$HERE"/fpga_list


if detect_brilliance; then
    RF_BOARD=BR
else
    RF_BOARD=EL
fi

case "$1" in
    sr) FPGA=FPGA_SR_$RF_BOARD ;;
    bo) FPGA=FPGA_BO_$RF_BOARD ;;
    *)  Error Must specify location correctly: sr or bo
esac
eval 'FPGA="$'$FPGA'"'


# The rootfs should normally be read only, so remount it for our operations
# and put it back again afterwards.
mount -o remount,rw /
trap 'mount -o remount,ro /' EXIT

# Prepare the complete directory tree, including the state directory required
# by the EPICS driver.
mkdir -p /opt/lib /opt/bin /var/opt/state
mkdir -p /etc/libera
ln -fsn /var/opt/state /opt/state

# Install the FPGA images and support tools
cp "$HERE"/fp "$HERE"/fpga_init /opt/bin
cp "$HERE"/notch1 "$HERE"/notch2 "$HERE"/polyphase_fir /opt/lib
cp "$HERE"/$FPGA /opt/lib
ln -fsn $FPGA /opt/lib/main_diamond_sr.bin

# Install the libera configuration
cp "$HERE"/libera_sr "$HERE"/libera_bo /etc/libera
ln -fsn libera_$1 /etc/libera/libera

# Install the drivers.
MODULES="/lib/modules/$(uname -r)"
mkdir -p "$MODULES"
cp "$HERE"/../msp/msp.ko "$MODULES"
cp "$HERE"/../libera/libera.ko "$MODULES"
depmod
